// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqSqNTdesFiBB9SrwyenSajeEXf3fZCEs',
    appId: '1:367839936549:web:80be93547692ae64af7fcc',
    messagingSenderId: '367839936549',
    projectId: 'audioapp1-8c8da',
    authDomain: 'audioapp1-8c8da.firebaseapp.com',
    storageBucket: 'audioapp1-8c8da.firebasestorage.app',
    measurementId: 'G-RLM2M6MXCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwoXmnFcV_nxewmDD4DMuM_M2Al0F7pd0',
    appId: '1:367839936549:android:3f45f8f34857c170af7fcc',
    messagingSenderId: '367839936549',
    projectId: 'audioapp1-8c8da',
    storageBucket: 'audioapp1-8c8da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0A1DN73ku1QUHdzJoyJgcoR3y0vciDW4',
    appId: '1:367839936549:ios:bf2bfb7a4bacb49eaf7fcc',
    messagingSenderId: '367839936549',
    projectId: 'audioapp1-8c8da',
    storageBucket: 'audioapp1-8c8da.firebasestorage.app',
    iosBundleId: 'com.example.audioApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0A1DN73ku1QUHdzJoyJgcoR3y0vciDW4',
    appId: '1:367839936549:ios:bf2bfb7a4bacb49eaf7fcc',
    messagingSenderId: '367839936549',
    projectId: 'audioapp1-8c8da',
    storageBucket: 'audioapp1-8c8da.firebasestorage.app',
    iosBundleId: 'com.example.audioApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqSqNTdesFiBB9SrwyenSajeEXf3fZCEs',
    appId: '1:367839936549:web:20156e171d12e8dcaf7fcc',
    messagingSenderId: '367839936549',
    projectId: 'audioapp1-8c8da',
    authDomain: 'audioapp1-8c8da.firebaseapp.com',
    storageBucket: 'audioapp1-8c8da.firebasestorage.app',
    measurementId: 'G-Z58WTJCMJS',
  );
}
